name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pptx sample.md
          # --reference-doc AA_PowerPoint_Template.pptx
          
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
